#!/bin/bash
# ============================================================
# traefik-sync.sh — Traefik Manager Sync Engine
# https://github.com/youvaKA/Lxc_Traefik_Manager
# ============================================================

BASE_DOMAIN="yourdomain.com"
TRAEFIK_VMID="103"
TRAEFIK_DYNAMIC_DIR="/etc/traefik/dynamic"
LXC_CONF_DIR="/etc/pve/lxc"
LOG_FILE="/var/log/traefik-sync.log"
CERT_RESOLVER="letsencrypt"
HEALTH_TIMEOUT=5

# ── Helpers ──────────────────────────────────────────────────
log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"; }
traefik_exec() { pct exec "$TRAEFIK_VMID" -- "$@"; }

get_lxc_ip() {
    local vmid="$1"
    local ip
    ip=$(pct exec "$vmid" -- hostname -I 2>/dev/null | awk '{print $1}')
    [ -z "$ip" ] && ip=$(grep -oP 'ip=\K[0-9.]+' "/etc/pve/lxc/${vmid}.conf" 2>/dev/null | head -1)
    echo "$ip"
}

# ── Parse config from LXC notes ──────────────────────────────
# Supports:
#   #TRAEFIK_1_NAME=myapp
#   #TRAEFIK_1_PORT=3000
#   #TRAEFIK_1_SCHEME=https   (optional, default: http)
#   #TRAEFIK_1_NOAUTH=true    (optional, removes ip-whitelist)
get_traefik_services() {
    local vmid="$1"
    local conf="/etc/pve/lxc/${vmid}.conf"
    [ -f "$conf" ] || return

    # New format: TRAEFIK_N_
    local indices
    indices=$(grep -oP "^#TRAEFIK_\K[0-9]+" "$conf" 2>/dev/null | sort -un)

    for i in $indices; do
        local name port scheme noauth
        name=$(grep   "^#TRAEFIK_${i}_NAME="   "$conf" | cut -d'=' -f2 | tr -d '[:space:]')
        port=$(grep   "^#TRAEFIK_${i}_PORT="   "$conf" | cut -d'=' -f2 | tr -d '[:space:]')
        scheme=$(grep "^#TRAEFIK_${i}_SCHEME=" "$conf" | cut -d'=' -f2 | tr -d '[:space:]')
        noauth=$(grep -c "^#TRAEFIK_${i}_NOAUTH=true" "$conf" 2>/dev/null || true)
        [ -z "$name" ] || [ -z "$port" ] && continue
        scheme="${scheme:-http}"
        [ "${noauth:-0}" -gt 0 ] && scheme="noauth"
        echo "${name}:${port}:${scheme}"
    done

    # Legacy format: TRAEFIK_SUB_DOMAINE_NAME / TRAEFIK_PORT
    local lname lport lscheme lnoauth
    lname=$(grep   "^#TRAEFIK_SUB_DOMAINE_NAME=" "$conf" | cut -d'=' -f2 | tr -d '[:space:]')
    lport=$(grep   "^#TRAEFIK_PORT="             "$conf" | cut -d'=' -f2 | tr -d '[:space:]')
    lscheme=$(grep "^#TRAEFIK_SCHEME="           "$conf" | cut -d'=' -f2 | tr -d '[:space:]')
    lnoauth=$(grep -c "^#TRAEFIK_NOAUTH=true"    "$conf" 2>/dev/null || true)
    if [ -n "$lname" ] && [ -n "$lport" ]; then
        lscheme="${lscheme:-http}"
        [ "${lnoauth:-0}" -gt 0 ] && lscheme="noauth"
        echo "${lname}:${lport}:${lscheme}"
    fi
}

# ── Health check ─────────────────────────────────────────────
check_service() {
    local ip="$1" port="$2" scheme="$3"
    local code
    code=$(curl -sk -o /dev/null -w "%{http_code}" \
        --max-time "$HEALTH_TIMEOUT" "${scheme}://${ip}:${port}" 2>/dev/null)
    [ "$code" != "000" ]
}

# ── Generate Traefik YAML ─────────────────────────────────────
create_traefik_config() {
    local vmid="$1" subdomain="$2" port="$3" scheme="${4:-http}"

    local ip
    ip=$(get_lxc_ip "$vmid")
    if [ -z "$ip" ]; then
        log "WARN: LXC ${vmid} — IP not found, skipping"
        return 1
    fi

    # Health check
    local check_scheme="$scheme"
    [ "$scheme" = "noauth" ] && check_scheme="http"
    if ! check_service "$ip" "$port" "$check_scheme"; then
        log "WARN: LXC ${vmid} — ${check_scheme}://${ip}:${port} not responding, skipping"
        return 1
    fi

    # Build middleware list
    local middlewares transport_ref=""
    case "$scheme" in
        noauth) middlewares="        - security-headers"; scheme="http" ;;
        https)  middlewares="        - ip-whitelist\n        - security-headers"
                transport_ref="        serversTransport: insecure-transport" ;;
        *)      middlewares="        - ip-whitelist\n        - security-headers"; scheme="http" ;;
    esac

    local service_name="lxc-${vmid}-${subdomain}"
    local dest="${TRAEFIK_DYNAMIC_DIR}/${service_name}.yml"

    traefik_exec bash -c "cat > ${dest} << 'ENDOFFILE'
# Auto-generated by Traefik Manager
# https://github.com/youvaKA/Lxc_Traefik_Manager
# LXC VMID: ${vmid} | $(date '+%Y-%m-%d %H:%M:%S')
http:
  routers:
    ${service_name}:
      rule: \"Host(\`${subdomain}.${BASE_DOMAIN}\`)\"
      service: ${service_name}
      entryPoints:
        - websecure
      middlewares:
$(echo -e "${middlewares}")
      tls:
        certResolver: ${CERT_RESOLVER}

  services:
    ${service_name}:
      loadBalancer:
        servers:
          - url: \"${scheme}://${ip}:${port}\"
${transport_ref}
        passHostHeader: true
ENDOFFILE"

    log "OK: ${subdomain}.${BASE_DOMAIN} → ${scheme}://${ip}:${port}"
}

delete_traefik_config() {
    local vmid="$1"
    traefik_exec bash -c "rm -f ${TRAEFIK_DYNAMIC_DIR}/lxc-${vmid}-*.yml 2>/dev/null" || true
    log "OK: Routes removed for LXC ${vmid}"
}

process_lxc() {
    local vmid="$1"
    [ "$vmid" = "$TRAEFIK_VMID" ] && return
    [ -f "/etc/pve/lxc/${vmid}.conf" ] || return

    local -a services
    mapfile -t services < <(get_traefik_services "$vmid")
    [ ${#services[@]} -eq 0 ] && return

    delete_traefik_config "$vmid"

    for svc in "${services[@]}"; do
        IFS=':' read -r subdomain port scheme <<< "$svc"
        create_traefik_config "$vmid" "$subdomain" "$port" "$scheme"
    done
}

# ── Main ─────────────────────────────────────────────────────
case "$1" in
    add|modify)
        log "EVENT: $1 LXC $2"
        sleep 2
        process_lxc "$2"
        ;;
    remove)
        log "EVENT: remove LXC $2"
        delete_traefik_config "$2"
        ;;
    sync-all)
        log "Sync all LXC containers..."
        for conf in "${LXC_CONF_DIR}"/*.conf; do
            vmid=$(basename "$conf" .conf)
            [[ "$vmid" =~ ^[0-9]+$ ]] && process_lxc "$vmid"
        done
        log "Sync complete"
        ;;
    *)
        echo "Usage: $0 {add|modify|remove|sync-all} [VMID]"
        exit 1
        ;;
esac
